# Generated by Django 4.2.23 on 2025-09-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_add_image_to_subservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='subservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subservices/'),
        ),
    ]
