# Generated by Django 4.2.23 on 2025-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_remove_service_image_subservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('booking', 'Booking Service (Appointments)'), ('order', 'Order Service (Products)')], default='booking', max_length=10),
        ),
    ]
