# Generated by Django 4.2.23 on 2025-09-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
