# Generated by Django 4.2.23 on 2025-09-05 14:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_subservice_stock_alter_subservice_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='hairstyle',
            options={'verbose_name': 'Hair Style', 'verbose_name_plural': 'Hair Styles'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='subservice',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Sub Service', 'verbose_name_plural': 'Sub Services'},
        ),
        migrations.AlterModelOptions(
            name='wig',
            options={'verbose_name': 'Wig', 'verbose_name_plural': 'Wigs'},
        ),
        migrations.AlterModelOptions(
            name='wigorder',
            options={'ordering': ['-order_date'], 'verbose_name': 'Wig Order', 'verbose_name_plural': 'Wig Orders'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('momo', 'Mobile Money')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='wigorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+233123456789'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(limit_choices_to={'service_type': 'booking'}, on_delete=django.db.models.deletion.CASCADE, to='salon.service'),
        ),
        migrations.AlterField(
            model_name='hairstyle',
            name='service',
            field=models.ForeignKey(limit_choices_to={'service_type': 'booking'}, on_delete=django.db.models.deletion.CASCADE, related_name='hairstyles', to='salon.service'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='wig',
            name='service',
            field=models.ForeignKey(limit_choices_to={'service_type': 'order'}, on_delete=django.db.models.deletion.CASCADE, related_name='wigs', to='salon.service'),
        ),
        migrations.AlterField(
            model_name='wigorder',
            name='customer_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+233123456789'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='wigorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('momo', 'Mobile Money')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='wigorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wigorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
