# Generated by Django 4.2.23 on 2025-09-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_alter_appointment_options_alter_hairstyle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
