# Generated by Django 4.2.23 on 2025-09-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_productorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='payment_confirmed',
        ),
        migrations.AddField(
            model_name='productorder',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('momo', 'Mobile Money')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='productorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
