# Generated by Django 4.2.23 on 2025-09-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_remove_productorder_payment_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='subservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.subservice'),
        ),
    ]
