# Generated by Django 4.2.23 on 2025-09-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_appointment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('admin', 'Admin'), ('system', 'System')], max_length=20, null=True),
        ),
    ]
