# Generated by Django 4.2.23 on 2025-09-07 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0012_appointment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorder',
            options={'ordering': ['-order_date'], 'verbose_name': 'Product Order', 'verbose_name_plural': 'Product Orders'},
        ),
        migrations.AddField(
            model_name='productorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wigorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wigorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wig_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
